import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/app/globals.css';
import Header from '@/shared/components/layout/Header';
import QueryProvider from '@/shared/provider/QueryProvider';
import { Toaster } from 'sonner';
import { dehydrate, HydrationBoundary, QueryClient } from '@tanstack/react-query';
import { userQueryOptions } from '@/features/user/queries';
import LoginModal from '@/features/auth/components/ui/LoginModal';
import LoginModalTrigger from '@/features/auth/components/ui/LoginModalTrigger';
import { Suspense } from 'react';
import InterviewGenerationPollingListener from '@/features/interview/components/sections/InterviewGenerationPollingListener';
import StrategyGenerationPollingListener from '@/features/strategy/components/sections/StrategyGenerationPollingListener';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../shared/assets/fonts/PretendardVariable.woff2',
  display: 'block',
  weight: '100 900',
  variable: '--font-pretendard',
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(userQueryOptions());
  return (
    <html lang="ko" className={`${pretendard.variable} ${pretendard.className}`}>
      <body>
        <QueryProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <Header />
            {children}
            <StrategyGenerationPollingListener />
            <InterviewGenerationPollingListener />
            <Toaster richColors position="top-right" />
            <LoginModal />
            <Suspense>
              <LoginModalTrigger />
            </Suspense>
          </HydrationBoundary>
        </QueryProvider>
      </body>
    </html>
  );
}
